### PR TITLE
fix hardcoded typecast to (int) for SUM() and add MIN() and MAX() 

### PR DESCRIPTION
**Pull request by andrenam**
- fix hardcoded typecast to (int) for SELECT SUM(field) ... queries.
   for example SUM(..) over float fields are now cast to the respective datatype
   of the field.

 - implement SELECT MIN(..) and SELECT MAX(..) queries

### CODE REVIEW

**Comment by oscarotero** [comment]
Hi. Thanks for this. Just one thing: In order to avoid code duplication, I think it's better to have a trait (for example `CalcTrait`)  with the common functions for sum, min and max, so it could be used to to include more queries like avg, [etc](https://dev.mysql.com/doc/refman/5.5/en/group-by-functions.html)

**Comment by andrenam** [comment]
Hi, do you want to replace the `Sum`, `Min`, `Max` query classes with a generic aggregation query class with a trait? That will break backward compability by removing the sum query?

 Or do you still want the `Sum`, `Min`, `Max` query classes? Which code do you wantt o move to a trait?

**Comment by oscarotero** [comment]
I mean we can have the `Sum`, `Min`, `Max` classes, all of them using the same trait with the common funcions (`field()`, `run()`, etc), so the only differency between them is the aggregation function. Example:

```php
class Sum
{
    use AggregationTrait;
    const AGGREGATION_FUNCTION = 'SUM';
}
```

**Comment by andrenam** [comment]
I added an `AggregationTrait` as you suggested.

**Comment by oscarotero** [comment]
Thanks!

**Pull request merged**
